version: '3.9'
services:
  database:
    container_name: database
    image: cenoteando:database
    build:
      context: ./database
      target: database
      dockerfile: Dockerfile
    ports:
      - 8529:8529
    restart: unless-stopped
    env_file:
      - database/env/.env
    volumes:
      - /var/lib/arangodb3
      - /var/lib/arangodb3-apps

  frontend:
    container_name: frontend
    image: cenoteando:frontend
    build:
      context: ./frontend/
      target: production-stage
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - 80:80
    restart: unless-stopped
    env_file:
      - frontend/env/.env
    volumes:
      - ./frontend/nginx/error.log:/var/log/nginx/error.log
      - ./frontend/nginx/access.log:/var/log/nginx/access.log

  filerun_db:
    container_name: filerun_db
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: cenoteando_mysql_root_password
      MYSQL_USER: cenoteando_filerun_username
      MYSQL_PASSWORD: cenoteando_filerun_password
      MYSQL_DATABASE: cenoteando_filerun_database
    restart: unless-stopped
    volumes:
      - ./filerun/db:/var/lib/mysql

  filerun:
    container_name: filerun
    image: afian/filerun
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: cenoteando_filerun_database
      FR_DB_USER: cenoteando_filerun_username
      FR_DB_PASS: cenoteando_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_db
    links:
      - filerun_db:filerun_db
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./filerun/html:/var/www/html
      - ./filerun/files:/user-files