version: '3.9'
services:
  database:
    container_name: database
    image: cenoteando-database
    build:
      context: ./database
      target: database
      dockerfile: Dockerfile
    ports:
      - 8529:8529
    restart: unless-stopped
    env_file:
      - ./config/env/database.dev.env
    volumes:
      - /var/lib/arangodb3
      - /var/lib/arangodb3-apps

  frontend:
    container_name: frontend
    image: cenoteando-frontend
    build:
      context: ./frontend/
      target: production-stage
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/error.log:/var/log/nginx/error.log
      - ./config/nginx/access.log:/var/log/nginx/access.log